/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proje_2416501032;

import java.awt.List;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author mehme
 */
public class giris extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(giris.class.getName());
    
    private int hataliGiris = 0;

    
    
    /**
     * Creates new form giris
     */
    public giris() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        btnGiris = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Şifre Gİriniz");

        btnGiris.setText("Giriş");
        btnGiris.addActionListener(this::btnGirisActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(btnGiris)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnGiris)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirisActionPerformed
        // TODO add your handling code here:
        String girilenSifre = new String(jPasswordField1.getPassword()); 
        File sifreDosyasi = new File("C:\\P2Oyun\\TXTDosyalar\\sifre.txt");

        if (girilenSifre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lütfen bir şifre giriniz!");
            return;
        }

        try {
            
            if (!sifreDosyasi.exists() || sifreDosyasi.length() == 0) {
                FileWriter writer = new FileWriter(sifreDosyasi);
                writer.write(girilenSifre);
                writer.close();
                JOptionPane.showMessageDialog(this, "Yeni şifreniz başarıyla kaydedildi! Şimdi giriş yapabilirsiniz.");
                jPasswordField1.setText(""); // Kutuyu temizle
                
                logKaydet("Yeni şifre belirlendi");
            } 
            
            else {
                BufferedReader reader = new BufferedReader(new FileReader(sifreDosyasi));
                String gercekSifre = reader.readLine();
                reader.close();

                if (girilenSifre.equals(gercekSifre)) {
                    JOptionPane.showMessageDialog(this, "Giriş Başarılı! Oyun açılıyor...");
                    
                    logKaydet("Başarılı giriş yapıldı");
                    
                    ana oyunEkrani = new ana();
                    oyunEkrani.setVisible(true);

                    
                    this.dispose();
                    
                } else {
                    hataliGiris++;
                    int kalanHak = 3 - hataliGiris;
                    
                    logKaydet("Hatalı giriş denemesi yapıldı (" + hataliGiris + ". hata)");
                    
                    if (kalanHak > 0) {
                        JOptionPane.showMessageDialog(this, "Hatalı şifre! Kalan hakkınız: " + kalanHak);
                        jPasswordField1.setText("");
                    } else {
                        JOptionPane.showMessageDialog(this, "3 kez hatalı giriş yaptınız. Program kapanıyor.");
                        System.exit(0); 
                    }
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Dosya işlemi sırasında bir hata oluştu: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnGirisActionPerformed
    
    private void logKaydet(String islem) {
        try {
            
            String zaman = java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm:ss"));
            
            
            FileWriter writerLog = new FileWriter("C:\\P2Oyun\\TXTDosyalar\\log.txt", true); 
            writerLog.write(zaman + " - Etiket: " + islem + "\n");
            writerLog.close();
        } catch (Exception e) {
            System.out.println("Log yazılamadı: " + e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new giris().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGiris;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
